CREATE TABLE IF NOT EXISTS system_evaluations (
  id INT PRIMARY KEY AUTO_INCREMENT,
  respondent_name VARCHAR(120) NOT NULL,
  respondent_type ENUM('student', 'guidance_counselor', 'personnel', 'other') DEFAULT 'student',
  participant_signature TEXT NULL,
  consent_signed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  q1 TINYINT NOT NULL,
  q2 TINYINT NOT NULL,
  q3 TINYINT NOT NULL,
  q4 TINYINT NOT NULL,
  q5 TINYINT NOT NULL,
  q6 TINYINT NOT NULL,
  q7 TINYINT NOT NULL,
  q8 TINYINT NOT NULL,
  q9 TINYINT NOT NULL,
  q10 TINYINT NOT NULL,
  sus_score DECIMAL(5, 2) NOT NULL,
  comments TEXT NULL,
  user_id INT NULL,
  ip_address VARCHAR(45) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_system_eval_created (created_at)
);
